Overv/VulkanTutorial

- index.html
Mentioned Valve open source Intel drivers for Linux
> Added drivers section 

- index.html
Changed the Vulkan video with a better one of the same talk.
> Added better quality version of Vulkan and SPIR-V talk

- index.html
Added a short description and an embedded video to the "Vulkan on NVIDIA GPUs" talk by Piers Daniell.
> Added NVIDIA SIGGRAPH 15 Conference video

- 02_Development_environment.md
Pretty sure this is a copy-paste error :)
> Use apt to install libglm-dev

- 00_Introduction.md
Fix to problem discussed in #34 .
> Update link reference to available resource

- README.md
Instructions include
* What's needed in your php install
* How to patch and rebuild daux
* How to live-serve
* How to generate static files
> Add instructions on how to use daux to render the tutorial

- 03_Drawing_a_triangle/03_Drawing/01_Command_buffers.md
Changed firstIntance -> firstInstance
> Fix spelling of firstInstance

- 06_Texture_mapping/00_Images.md
staging image wasn't defined anywhere in the code up to this point.
> stagingImage to textureImage

- code/base_code.cpp
- code/command_buffers.cpp
- code/depth_buffering.cpp
- code/descriptor_layout.cpp
- code/descriptor_set.cpp
- code/fixed_functions.cpp
- code/framebuffers.cpp
- code/graphics_pipeline_complete.cpp
- code/hello_triangle.cpp
- code/image_views.cpp
- code/index_buffer.cpp
- code/logical_device.cpp
- code/model_loading.cpp
- code/render_passes.cpp
- code/sampler.cpp
- code/staging_buffer.cpp
- code/swap_chain_creation.cpp
- code/swap_chain_recreation.cpp
- code/texture_image.cpp
- code/texture_mapping.cpp
- code/vertex_buffer.cpp
- code/vertex_input.cpp
- code/window_surface.cpp
There was ~600 bytes worth white spaces I removed to help more in the future from propagating
> Removed white spaces

- 03_Drawing_a_triangle/01_Presentation/01_Swap_chain.md
Thanks for writing and maintaining this tutorial. I made a small grammar-related change which IMHO sounds better - no guarantees on correctness though.
> Small grammar change

- 05_Uniform_buffers/01_Descriptor_pool_and_sets.md
Changed `updateUniformData` to `updateUniformBuffer`.
> Fix a function name typo

- 09_Generating_Mipmaps.md
> Update text to add change to `transitionImageLayout`

- README.md
- daux.patch
1. Update github location for daux.io
2. Fix non-unique ids on Development Environment page by backporting a Table of Contents fix from daux.io
> Updates from dauxio

- 10_Multisampling.md
Updates recreateSwapChain to allow for window resizing.
Adds clear values for the newly created attachment in createCommandBuffers.
> Updates to Multisampling chapter

- 03_Drawing_a_triangle/04_Swap_chain_recreation.md
Hey there, I've found this small typo today while reading the tutorial. I hope I got the sense right and the "talking about the past at some future time" is correct here.
Cheers
> Fix a small typo

- 01_Overview.md
I'm not sure whether this should be "set" or "known".
> Added missing word

- fr/03_Dessiner_un_triangle/00_Mise_en_place/02_Validation_layers.md
to specify that debug messengers are optional. ( commit 3917f839e26f4965b37f63b71b160be73e201fa7 )
> Change validation layer chapter translation

- fr/00_Introduction.md
- fr/02_Environnement_de_développement.md
- fr/03_Dessiner_un_triangle/00_Mise_en_place/03_Physical_devices_et_queue_families.md
- fr/03_Dessiner_un_triangle/02_Pipeline_graphique_basique/01_Modules_shaders.md
- fr/03_Dessiner_un_triangle/03_Effectuer_le_rendu/01_Command_buffers.md
- fr/03_Dessiner_un_triangle/03_Effectuer_le_rendu/02_Rendu_et_présentation.md
- fr/03_Dessiner_un_triangle/04_Recréation_de_la_swap_chain.md
- fr/04_Vertex_buffers/02_Buffer_intermédiaire.md
- fr/05_Uniform_buffers/01_Descriptor_pool_et_sets.md
- fr/07_Buffer_de_profondeur.md
- fr/10_Multisampling.md
Took the different commits since last translation update and translated the new parts added to the tutorial.
I wouldn't mind someone looking at it to be sure there is no typos or inconsistencies.
> French update

- fr/03_Dessiner_un_triangle/03_Effectuer_le_rendu/02_Rendu_et_présentation.md
> Update French translation

- en/02_Development_environment.md
- fr/02_Environnement_de_développement.md
Following 'Introduction' changes in 53b2e684fc6898f6e15e8789ffa3aea2118dfffd.
> Dev env: Update min compiler requirements for C++17

- README.md
> fix #171 boken links; E-book epub/pdf

- en/02_Development_environment.md
Updates to Linux instructions based on Overv's [request](https://github.com/Overv/VulkanTutorial/issues/189#issuecomment-673044366):
1. GLFW is now installed from a standard package.
2. Install standard Vulkan packages that are more up-to-date than the LunarG SDK. This gives us Ubuntu 20.04 support.
3. Update Makefile instructions to reflect the above changes.
> Dev env: fix #189; setting up Vulkan on Linux needs updates

- fr/02_Environnement_de_développement.md
- fr/05_Uniform_buffers/00_Descriptor_layout_et_buffer.md
- fr/05_Uniform_buffers/01_Descriptor_pool_et_sets.md
- fr/07_Buffer_de_profondeur.md
- fr/09_Générer_des_mipmaps.md
- fr/90_FAQ.md
The goal of this PR is to reflect the latest changes from master (english version) in the french version.
Moreover, I have fixed some small typos while reading the changes ;).
> Sync french translations with the latest changes from master

- en/06_Texture_mapping/02_Combined_image_sampler.md
The way that `vkAllocateDescriptorSets` handles errors from inadequate pools was changed in `VK_KHR_maintenance1`, which was promoted to core in Vulkan 1.1:
> If a call to `vkAllocateDescriptorSets` would cause the total number of descriptor sets allocated from the pool to exceed the value of `VkDescriptorPoolCreateInfo::maxSets` used to create `pAllocateInfo->descriptorPool`, then the allocation *may* fail due to lack of space in the descriptor pool. Similarly, the allocation *may* fail due to lack of space if the call to `vkAllocateDescriptorSets` would cause the number of any given descriptor type to exceed the sum of all the `descriptorCount` members of each element of `VkDescriptorPoolCreateInfo::pPoolSizes` with a member equal to that type.
This means that in Vulkan `>=1.1`, there …
> Fix description of vkAllocateDescriptorSets error

- code/05_window_surface.cpp
- en/03_Drawing_a_triangle/01_Presentation/00_Window_surface.md
We need to define VkWin32SurfaceCreateInfoKHR before including GLFW header.
> VkWin32SurfaceCreateInfoKHR not defined

- config.json
Keep consistent with https://github.com/Overv/daux.io/pull/1.
> Use native language name in "languages" option.

- en/00_Introduction.md
Requested edit to add the new SoC by Apple, the Apple Silicon or the m1,
> Apple M1 Added

- code/23_texture_image.cpp
- code/24_sampler.cpp
- code/25_texture_mapping.cpp
- code/26_depth_buffering.cpp
- code/27_model_loading.cpp
- code/28_mipmapping.cpp
- code/29_multisampling.cpp
- en/06_Texture_mapping/00_Images.md
- fr/06_Texture_mapping/00_Images.md
This is a simple search and replace as proposed in the request. It does actually make changes in some markdown text too, but only those that can be made automatically. I have not check whether some of the explaining text would have to be changed too.
> Request #251: stb directory for stb include files

- en/10_Multisampling.md
Change createFrameBuffers to createFramebuffers because it's written as "createFramebuffers" in the source code
> Change createFrameBuffers to createFramebuffers

- en/03_Drawing_a_triangle/04_Swap_chain_recreation.md
I think there meant to be "to get"
> Added missing "to"

- code/22_descriptor_set_layout.cpp
- code/CMakeLists.txt
- en/05_Uniform_buffers/00_Descriptor_set_layout_and_buffer.md
- en/05_Uniform_buffers/01_Descriptor_pool_and_sets.md
- en/06_Texture_mapping/02_Combined_image_sampler.md
> replace "descriptor layout" with "descriptor set layout"

- en/03_Drawing_a_triangle/04_Swap_chain_recreation.md
- fr/03_Dessiner_un_triangle/04_Recréation_de_la_swap_chain.md
Following the changes in this commit: https://github.com/Overv/VulkanTutorial/commit/e5846255c4c2cddebe658a6c7e0af84d2e3828e1
Updating the markdown files to be consistent.
> Use range-based loops in markdown
