index.html

Khronos released new slides about Vulkan; I couldn't find a link to the original slides, so I linked two articles by Anandtech and Phoronix.
ImgTech also released a new demo, so I linked that video as well.

Add link to new Khronos slides and new ImgTech demo

---

index.html

Added a link to the recent LunarG video of their LunarXCHange. It's the Vulkan Developer platform, also showcasing some of the Vulkan documentation and tools.

Added LunarXChange Videolink

---

03_Drawing_a_triangle/00_Setup/03_Physical_devices_and_queue_families.md

In one of the early, intermediate representations of isDeviceSuitable
the code uses the class variable 'physicalDevice' instead of the
argument passed in, 'device'.
Even though this code is iterated on, and not in the final version
presented in this section, using the proper variable makes this
code easier to follow.

Code improvement for intermediate isDeviceSuitable

---

03_Drawing_a_triangle/00_Setup/02_Validation_layers.md

There was a typo in the paragraph above the code example: `setupDebugCallback` != `createDebugCallback`
This fixes it.

Fix incorrect function name in example

---

08_Loading_models.md
code/model_loading.cpp

When running the given examples I had an all black screen.
I realized the shader was still multiplying the texture and vertex
colors. This sets each color to white as they are loaded from the obj.
An alternative solution would be to modify the fragment shader,
but felt it was better to provide proper Vertex attributes.

Load models section needs vertex colors

---

03_Drawing_a_triangle/00_Setup/03_Physical_devices_and_queue_families.md

This fixes a typo where something like "are" seems to be missing.
Furthermore, it seems to me that the device scoring example on the same page is broken since std::map will sort the devices in order of increasing score (as stated in the example), but then the "best" device is accessed using ```candidates.begin()```, which will return the device with the lowest score. Thus, it will actually return the worst device. I changed it to use ```candidates.rbegin()``` to access the best device instead. While at it, I would also propose to use a ```std::multimap``` here such that multiple devices with the same score won't get merged into a single map entry (might potentially be useful if one wants to optionally show the sorted device list to the user, for example). ```std::multimap``` does not seem …

Fix device scoring example and a typo

---

02_Development_environment.md

Resolving `[text](!other_page)` links appears to be more lenient in live-serving mode, where if you give it a base directory and not a leaf file it works (figuring out the leaf file on the fly). However this breaks static generation because it complains it can't find the directory as a doc file.
This pull request fixes two "broken" links in the tutorial by pointing them at the first leaf file in the sub-directory hierarchy instead of at the base directory. It has no affect on the live serving because we simply made the link more accurate.

Fix link references so that the Daux static file generator works

---

06_Texture_mapping/00_Images.md

in the text it says we'll be using VK_IMAGE_TILING_OPTIMAL, but the code had it set to VK_IMAGE_TILING_LINEAR. Also the code further down the page has it set to VK_IMAGE_TILING_OPTIMAL.

VK_IMAGE_TILING_LINEAR to VK_IMAGE_TILING_OPTIMAL

---

03_Drawing_a_triangle/01_Presentation/01_Swap_chain.md

I was quite puzzled by the words <<images to render to that>>, maybe because I am not a native but it took me more than one read to understand it :D This is a proposed change, maybe not the best, but I am opening the PR so that maybe you can evaluate whether to change the sentence in some way or not. A minor thing but the quality of the tutorials is pretty high hence I hope it's not a problem I am raising even smaller issues.

Small change in the text that introduces swap chains

---

03_Drawing_a_triangle/00_Setup/01_Instance.md
03_Drawing_a_triangle/00_Setup/02_Validation_layers.md

glfwGetRequiredInstanceExtensions takes a uint32_t, and it's best for portable code to be explicit in its types.
Similar code in this section also explicitly uses uint32_t

Fix type inconsistency.

---

06_Texture_mapping/01_Image_view_and_sampler.md
code/depth_buffering.cpp
code/model_loading.cpp
code/sampler.cpp
code/texture_mapping.cpp

The code and relevant example(s) were missing the check for swapChainAdequate in the isDeviceSuitable function, starting in the Image View and Sampler code example.

Fix Image View and Sampler code and beyond missing swapChainAdequate check

---

07_Depth_buffering.md

The call to cleanupSwapChain was missing in the example for recreateSwapChain  at the end of the depth buffering page.

Depth buffering recreateSwapChain example missing call to cleanupSwapChain

---

09_Generating_Mipmaps.md

Fixes typo in chapter. Fixes #78. Adds extra explanation for the image layout transitions.

Update Generating Mipmaps chapter

---

03_Drawing_a_triangle/02_Graphics_pipeline_basics/04_Conclusion.md

The original text mentions to add the VkGraphicsPipelineCreateInfo & vkCreateGraphicsPipelines() at the end of createGraphicsPipeline(). However they should be called before the calls to vkDestroyshaderModule as these are referenced inside the pipelineInfo struct. If you add them at the end (after the destruction, and as the text mentions) you'll get errors like: 
(null)(ERROR / SPEC): msgNum: 274780673 - Invalid ShaderModule Object 0xa. The spec valid usage text states 'module must be a valid VkShaderModule handle' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkPipelineShaderStageCreateInfo-module-parameter)
Objects: 1
[0] 0xa, type: 15, name: (null)

04_Conclusion.md: Clarify vkCreateGraphicsPipeline location

---

03_Drawing_a_triangle/01_Presentation/01_Swap_chain.md

Thank you for the tutorial I've finally got my triangle on screen. 🙂 
However I've sucked with swapchain initialization with vulkansdk 1.1.85.0 because debug layers didn't tell me about missed extension during debug initialization and I've gone wrong way because was thinking that the problem is in MoltenVK.
So, at the end I rolled back to 1.1.77.0 and debug layers showed me the problem. So, I decided to highlight this step  to help future adventurers. 🙂

Highlighted enabling device extensions section

---

02_Development_environment.md

At least on debian (testing) the binary that is built is called 'vkcube', not 'cube'.

Refer to actual binary name

---

06_Texture_mapping/00_Images.md

The "STBI_rgb_alpha" constant name was incorrect.

Corrected minor typo in Texture_mapping/00_Images.md

---

en/00_Introduction.md

Considering this tutorial is currently using C++17 feature (`std::optional`), it should require people to have a recent enough compiler.

Update required C++ and compiler version

---

en/02_Development_environment.md
en/03_Drawing_a_triangle/02_Graphics_pipeline_basics/01_Shader_modules.md
en/04_Vertex_buffers/01_Vertex_buffer_creation.md

Here are some typos I found while reading.
Also, I'm not sure if this is intended or not but starting from the `01_Vertex_buffer_creation.md` chapter onwards, there is an unusual indentation in the code line with `    memcpy(data, vertices.data(), (size_t) bufferInfo.size);`, both in that page itself, and in the accompanying C++ code for that page (and all subsequent pages/code samples in the following chapters, AFAIK). I haven't done anything about that since I don't know if this is intended or not.
P.S. Thanks for the amazing tutorial!

Fixed some typos

---

en/03_Drawing_a_triangle/00_Setup/00_Base_code.md

Thanks for the tutorial. I'm starting to learn Vulkan :) 
I turned on my personal `-Wpedantic` flag and improved some sentences regarding C++, also removed an unused header. 
Rationale:
* `<functional>` is not used anywhere. There's no such thing as a *"lambda function"* in C++ - we have *lambda expressions* which are a core language feature that does **not** require use of the `<functional>` header, and we have `std::function` which is a general-purpose callable object wrapper that **supports** closures generated by *lambda expressions*, but it is not directly related to them. `std::function` is a heavyweight abstraction and it is **not** the type of a closure generated by a *lambda expression* - the latter is an anonymous unique type generated by the compiler.
* "Automatic resource …

Remove unused header and improve C++ wording

---

en/03_Drawing_a_triangle/00_Setup/01_Instance.md

Rationale:
* "Default initialization" actually means not initializing the object, which would leave it uninitialized. Using `= {}` is "aggregate initialization" syntax, which leads to "value initialization". Directly using `{}` is just "value initialization". 
* `std::endl` is overused and can be a source of performance issues, as it forces the output buffer to be flushed. `\n` is - most of the times - what you need. Just doing my part in trying to avoid overuse of `std::endl`.

Improve wording and C++ usage in 01_Instance

---

fr/03_Dessiner_un_triangle/02_Pipeline_graphique_basique/03_Render_pass.md

hi, i don't really know how to contribute but i have found a little mistake (confusion between before and after in the french translation). It's in the render pass chapter, part "setup".
btw i want to thanks you for all the work you have done.

confusion between before and after in the french translation

---

code/24_sampler.cpp
code/25_texture_mapping.cpp
code/26_depth_buffering.cpp
code/27_model_loading.cpp
code/28_mipmapping.cpp
code/29_multisampling.cpp
en/06_Texture_mapping/01_Image_view_and_sampler.md
en/09_Generating_Mipmaps.md
fr/06_Texture_mapping/01_Vue_sur_image_et_sampler.md
fr/09_Générer_des_mipmaps.md

I've noticed that four members of the `VkSamplerCreateInfo` struct are floats, but assigned integer values in various places. Although implicit type conversion will be performed at compile time, I think this should be changed because of two reasons:
1. Assigning integer values to the members may lead to the assumption that the members itself are of an integer type. This wrong assumption may lead to trouble (missing casts, invalid bitwise operations).
2. The member types are an important semantic clue (f.i. one could assume that `maxAnisotropy` might represent a number of samples, whereas this idea does not seem probable when looking at a float assignment). 
The definition of `VkSamplerCreateInfo` as of Vulkan 1.2 can be found [here](https://www.khronos.org/registry/vulkan/specs/1.2-extensi …

Fix VkSamplerCreateInfo type assignments

---

en/03_Drawing_a_triangle/01_Presentation/01_Swap_chain.md

fix just a typo on the word "transfered" that should be spelled transferred

fix typo in 01_Swap_chain.md

---

en/09_Generating_Mipmaps.md

I'm not sure if this fits stylistically. :)
All my queues have graphics capability, so I can't check what the validation layer may have to say about using a transfer-only queue.

Add remark regarding queue type for vkCmdBlitImage

---

code/06_swap_chain_creation.cpp
code/07_image_views.cpp
code/08_graphics_pipeline.cpp
code/09_shader_modules.cpp
code/10_fixed_functions.cpp
code/11_render_passes.cpp
code/12_graphics_pipeline_complete.cpp
code/13_framebuffers.cpp
code/14_command_buffers.cpp
code/15_hello_triangle.cpp
en/03_Drawing_a_triangle/01_Presentation/01_Swap_chain.md
en/03_Drawing_a_triangle/04_Swap_chain_recreation.md

When using an HDPI display, using the window size `{WIDTH, HEIGHT}` to determine swapchain image size is incorrect. See the following links:
* https://www.glfw.org/docs/latest/window.html#window_size
* https://www.glfw.org/docs/latest/window.html#window_fbsize
* https://www.glfw.org/faq.html#43---why-is-my-output-in-the-lower-left-corner-of-the-window
Short version: The window size in GLFW is specified in screen coordinates, but Vulkan requires the swapchain image extent to be specified in pixel. On HDPI displays, these are not the same thing.
Instead, the framebuffer size is now used to determine the swapchain extent. Using the implementation of `chooseSwapExtent` from `16_swap_chain_recreation.cpp` seemed appropriate. Beyond "Swap chain recreation" no changes are necessary.
I'm a little …

Fix else branch of chooseSwapExtent for HDPI/retina displays

---

en/02_Development_environment.md

Following along with the tutorial, I noticed that the GLFW Homebrew package had been renamed from `glfw3` to `glfw`.
Additionally, the latest available version already has the necessary Vulkan support, so it is no longer necessary to install using `--HEAD`.

Update GLFW setup instructions for macOS

---

en/02_Development_environment.md

When doing the [validation layers tutorial](https://vulkan-tutorial.com/Drawing_a_triangle/Setup/Validation_layers), compiling and running the example produced the following error message:
```                                                                              
validation layer: libSPIRV-Tools-opt.so: cannot open shared object file: No such file or directory  
```
and no other validation layer output. After some Googling, I discovered that installing `spirv-tools` fixes the above error message, and causes the expected validation layer messages to appear:
```
VUID-VkDebugUtilsMessengerCreateInfoEXT-flags-zerobitmask(ERROR / SPEC): msgNum: 0 - vkCreateDebugUtilsMessengerEXT: parameter pCreateInfo->flags must be 0. The Vulkan spec states: flags must be 0 …
```

Add `spirv-tools` package to 02_Development_environment.md

---

code/02_validation_layers.cpp
code/03_physical_device_selection.cpp
code/04_logical_device.cpp
code/05_window_surface.cpp
code/06_swap_chain_creation.cpp
code/07_image_views.cpp
code/08_graphics_pipeline.cpp
code/09_shader_modules.cpp
code/10_fixed_functions.cpp
code/11_render_passes.cpp
code/12_graphics_pipeline_complete.cpp
code/13_framebuffers.cpp
code/14_command_buffers.cpp
code/15_hello_triangle.cpp
code/16_swap_chain_recreation.cpp
code/17_vertex_input.cpp
code/18_vertex_buffer.cpp
code/19_staging_buffer.cpp
code/20_index_buffer.cpp
code/21_descriptor_layout.cpp
code/22_descriptor_sets.cpp
code/23_texture_image.cpp
code/24_sampler.cpp
code/25_texture_mapping.cpp
code/26_depth_buffering.cpp
code/27_model_loading.cpp
code/28_mipmapping.cpp
code/29_multisampling.cpp
en/03_Drawing_a_triangle/00_Setup/02_Validation_layers.md
fr/03_Dessiner_un_triangle/00_Mise_en_place/02_Validation_layers.md

It is always good practice to initialize structs even if they aren't used, as it makes it more consistent with everywhere else and the compiler is perfectly capable of eliminating dead stores.
Resolves issue #217

Initialize debugCreateInfo everywhere

---

code/14_command_buffers.cpp
code/15_hello_triangle.cpp
code/16_swap_chain_recreation.cpp
code/17_vertex_input.cpp
code/18_vertex_buffer.cpp
code/19_staging_buffer.cpp
code/20_index_buffer.cpp
code/21_descriptor_layout.cpp
code/22_descriptor_sets.cpp
code/23_texture_image.cpp
code/24_sampler.cpp
code/25_texture_mapping.cpp
code/26_depth_buffering.cpp
code/27_model_loading.cpp
code/28_mipmapping.cpp
code/29_multisampling.cpp
en/03_Drawing_a_triangle/03_Drawing/01_Command_buffers.md
en/07_Depth_buffering.md
fr/03_Dessiner_un_triangle/03_Effectuer_le_rendu/01_Command_buffers.md
fr/07_Buffer_de_profondeur.md

`clang++ -Wall` emits the warning "suggest braces around initialization of subobject [-Wmissing-braces]" with code like
```cpp
VkClearValue clearColor = {0.0f, 0.0f, 0.0f, 1.0f};
```
Since this is trying to fill out `clearColor.color.float32`, 3 braces are needed like
```cpp
VkClearValue clearColor = {{{0.0f, 0.0f, 0.0f, 1.0f}}};
```
to avoid the warning.

Add extra braces when setting VkClearValue

---

code/.gitignore
code/CMakeLists.txt

Calling `cmake --build .` will build the sample code executables for each
chapter in it's own folders, compile corresponding shaders and copy all
required resources to appropriate sub-folders. After that any example is
ready to be run from it's build sub-folder.
CMake project requires following dependencies:
* glfw3 dev package
* glm dev package
* stb_image header
* tinyobjloader dev package
* Vulkan sdk

Code samples: add CMakeLists.txt

---

en/00_Introduction.md

It looks like the repo https://github.com/RayTracing/InOneWeekend now points to https://github.com/RayTracing/raytracing.github.io . Updated the link to reflect this.

Update link to Ray Tracing book

---

en/03_Drawing_a_triangle/01_Presentation/01_Swap_chain.md
fr/03_Dessiner_un_triangle/01_Présentation/01_Swap_chain.md

I suspect the example code used `std::min` and `std::max` and was later changed to `std::clamp`.

Mention std::clamp in explanatory comment instead of min/max

---

fr/06_Texture_mapping/00_Images.md

vkBindBuffer was mistyped as vkBingBuffer in the french translation, also leading to a non-existant page on the specification.

Fix minor typo in french translation

---

fr/06_Texture_mapping/00_Images.md

Fixes what has been discussed here: https://github.com/Overv/VulkanTutorial/pull/258

Add full name for vkBindXMemory functions in french translation

---

en/02_Development_environment.md

Added Arch Linux support, plus a "`make`" formatting fix. Should resolve #238.

Add Arch Linux support

---

en/05_Uniform_buffers/01_Descriptor_pool_and_sets.md
fr/05_Uniform_buffers/01_Descriptor_pool_et_sets.md

The **vkDestroyDescriptorPool** is missing from the tutorial and vulkan gives a warning for it.
However it is present in the code examples in the github repo: [23_descriptor_sets.cpp](https://github.com/Overv/VulkanTutorial/blob/master/code/23_descriptor_sets.cpp)

vkDestroyDescriptorPool added to Descriptor pool and sets

---

en/05_Uniform_buffers/00_Descriptor_layout_and_buffer.md
en/05_Uniform_buffers/01_Descriptor_pool_and_sets.md

This commit removes leftover references to the number of swapchain
images in the "Uniform buffers" chapter.
This seems to be an error introduced by the https://github.com/Overv/VulkanTutorial/pull/255 PR.
Just wanted to say a big THANK YOU to everyone who has contributed to this tutorial, it's the only thing making Vulkan approachable!

Remove outdated reference to swapchain

---

en/07_Depth_buffering.md

This code was still refering to `createCommandBuffers`  instead of `recordCommandBuffer`.

Fix small problem in "Depth buffering"

---

code/10_fixed_functions.cpp
code/11_render_passes.cpp
code/12_graphics_pipeline_complete.cpp
code/13_framebuffers.cpp
code/14_command_buffers.cpp
code/15_hello_triangle.cpp
code/16_frames_in_flight.cpp
code/17_swap_chain_recreation.cpp
code/18_vertex_input.cpp
code/19_vertex_buffer.cpp
code/20_staging_buffer.cpp
code/21_index_buffer.cpp
code/22_descriptor_layout.cpp
code/23_descriptor_sets.cpp
code/24_texture_image.cpp
code/25_sampler.cpp
code/26_texture_mapping.cpp
code/27_depth_buffering.cpp
code/28_model_loading.cpp
code/29_mipmapping.cpp
code/30_multisampling.cpp
en/03_Drawing_a_triangle/02_Graphics_pipeline_basics/02_Fixed_functions.md
en/03_Drawing_a_triangle/02_Graphics_pipeline_basics/04_Conclusion.md
en/03_Drawing_a_triangle/03_Drawing/01_Command_buffers.md
en/03_Drawing_a_triangle/04_Swap_chain_recreation.md

This PR updates the tutorial to use dynamic state for viewport and scissor rectangles. This simplifies things a lot and no longer requires e.g. pipelines and render passes to be recreated with the swap chain on window resize.
* Update chapter "Fixed function":
* Better wording on baked state in pipeline state objects
* Moved dynamic state paragraph to the top and also slightly reworded it
* Updated the viewport and scissor state chapter with dynamic state and why it's better to use this instead of baking it
* Update chapter "Command buffers"
* Added viewport and scissor setup to command buffer recording
* Update chapter "Swapchain recreation"
* With dynamic state for viewport and scissor, it's no longer required to recreate pipeline and render pass when the swapchain is recreated
* Update …

Update tutorial to use dynamic state for viewport and scissor 

---

en/07_Depth_buffering.md

Fix the recreateSwapChain() function to match the code, which may cause the "Validation Error" if you resize and close window.

Fix the recreateSwapChain() function in 07_Depth_buffering.md 

---

en/03_Drawing_a_triangle/00_Setup/01_Instance.md

Accroding to MoltenVK release notes, the `VK_KHR_PORTABILITY_subset` extension is mandatory. Otherwise `vkCreateInstance` will generate `VK_ERROR_INCOMPATIBLE_DRIVER` error.
So I append a new section in Instance creation chapter to show how to fix this error. I think this is helpful for beganners with MacOS.

Append new section in 01_Instance.md

---

en/02_Development_environment.md

On Fedora, the packages should be libXi-devel and libXxf86vm-devel, instead of libXi and libXxf86vm. Otherwise, by following the tutorial, we might get errors such as:
```
/usr/bin/ld: cannot find -lXxf86vm
collect2: error: ld returned 1 exit status
make: *** [Makefile:5: VulkanTest] Error 1
```

Change Fedora packages' names

---

code/22_descriptor_layout.cpp
code/23_descriptor_sets.cpp
code/24_texture_image.cpp
code/25_sampler.cpp
code/26_texture_mapping.cpp
code/27_depth_buffering.cpp
code/28_model_loading.cpp
code/29_mipmapping.cpp
code/30_multisampling.cpp
en/05_Uniform_buffers/00_Descriptor_layout_and_buffer.md

This PR changes how the tutorial maps uniform buffers for updating. Instead of mapping and unmapping each frame, they are now mapped once after creation ("persistent mapping").
The PR updates both the tutorial chapter (that talks about ubos) and all code snippets that make use of ubos.

Persistent mapping for uniform buffers

---

code/15_hello_triangle.cpp
en/03_Drawing_a_triangle/03_Drawing/02_Rendering_and_presentation.md

This PR is a collection of minor formatting fixes that I believe could be improved. In especial, the commit [Add three dots to indicate that it isn't the top of the function](https://github.com/Overv/VulkanTutorial/commit/80b9d8e6fc0113f8835b7fb2900dd776f321e36e), as it was a bit confusing for me, as a reader, to understand if the code should or should not be placed on top of the function `drawFrame()`.

A collection of minor fixes

---

en/02_Development_environment.md

Makefile requires usage of tabs for indentation, otherwise it throws `*** missing separator.  Stop.`

Change Makefile snippets to use tabs

---

code/25_sampler.cpp
code/26_texture_mapping.cpp
code/27_depth_buffering.cpp
code/28_model_loading.cpp
code/29_mipmapping.cpp
code/30_multisampling.cpp
en/06_Texture_mapping/01_Image_view_and_sampler.md

The function "createImageView" has a somewhat incorrect error message, saying that it failed to create a texture image view. However, the function is also used by more than simply the texture image view creation process(e.g., the swapchain image view creation process, "createImageViews").
This patch is applied to all subject code files, and the English "06_Texture_mapping/01_Image_view_and_sampler.md" file has also been modified.
The French version of the markdown file remains unchanged due to my lack of knowledge about French, but probably should be changed in the near future to maintain consistency.

Fix incorrect create image view error message

---

en/03_Drawing_a_triangle/02_Graphics_pipeline_basics/01_Shader_modules.md
fr/03_Dessiner_un_triangle/02_Pipeline_graphique_basique/01_Modules_shaders.md

The latest Vulkan SDK doesn't have the `Bin32` directory.
For example, the path in 1.3.243.0 is:
```
C:/VulkanSDK/1.3.243.0/Bin/glslc.exe
```

Fix Vulkan SDK path on Windows

---

en/00_Introduction.md

The [vulkanalia-based tutorial](https://kylemayes.github.io/vulkanalia/) is
- Based on a much "lower level" crate `vulkanalia`, which is much closer to raw Vulkan API calls
- Also ships explanatory texts and discussed some Rust side practices
- *Completed*
Safe Rust is good, but it's also meaningful to have an alternative version, I think. Maybe we should even put the vulkanalia version ahead since it's more accomplished.

Add another good Rust tutorial

---

code/CMakeLists.txt

This PR conditionally adds compute shaders to the build process. If such a shader type is present (e.g. for the compute bonus chapter) it's added to build such that the corresponding SPIR-V file will be generated at compile time.
Fixes #351 
Fixes #361

Add compute shader compilation to cmake

---

LICENSE.CC-BY-SA-40
LICENSE.CC0
en/00_Introduction.md

Add the license files so that github can correctly detect the licenses.
The readers of https://vulkan-tutorial.com/ would not know the license information unless they come to this repo. Add a license section in the introduction can clarify that, and make the website/ebook more compliant.

Add license files and a license section in introduction

---

en/02_Development_environment.md

Arch Linux doesn't have separate `glfw-wayland` and `glfw-x11` packages now. [(arch package search for "glfw")](https://archlinux.org/packages/?sort=&q=glfw&maintainer=&flagged=)

Update Chapter 2 to reflect that Arch Linux only has one glfw package now

---

en/03_Drawing_a_triangle/02_Graphics_pipeline_basics/02_Fixed_functions.md

There was an extra "is" after "it's".

Fix a typo

---

en/02_Development_environment.md

Xxf68vm is supposed to be Xxf86vm.

Fix Xxf68vm typo

---

en/02_Development_environment.md
fr/02_Environnement_de_développement.md

[EN]
The second section, called development environment, suggests to install the `mesa-vulkan-devel` on Fedora. This package does not exist since version 36. The current version is 41. It has been replaced with `mesa-vulkan-drivers`. I tested it. For an additional source, see : https://discussion.fedoraproject.org/t/what-is-the-f36-version-of-the-package-mesa-vulkan-devel/74573/4
[FR]
La seconde section, appelée « Environnement de développement », suggère d'installer le paquet `mesa-vulkan-devel` sur Fedora. Or ce paquet n'existe plus depuis la version 36. La version courante est la 41. Le paquet a été remplacé par `mesa-vulkan-drivers`. Je l'ai testé. Pour une source additionnelle, voir : https://discussion.fedoraproject.org/t/what-is-the-f36-version-of-the-package-mesa-vulkan-devel/74573 …

Replace mesa-vulkan-devel with mesa-vulkan-drivers in Fedora

---

code/28_model_loading.cpp
code/29_mipmapping.cpp
code/30_multisampling.cpp
en/08_Loading_models.md
fr/08_Charger_des_modèles.md

Original issue: https://github.com/Overv/VulkanTutorial/issues/404
There is no function in the current implementation of TinyObjLoader which accepts more than one string in its arguments for error logging. Because of this, the unfixed example code causes a compilation failure.
To fix this, I removed the "warn" string passed to the tinyobj::loadObject(...) function, in the example code for chapters 28, 29, and 30; I also updated the code in both languages of the Loading Models chapter.

Remove invalid "warn" argument passed to tinyobj::loadObject(...)

---

README.md
en/03_Drawing_a_triangle/00_Setup/00_Base_code.md

I was attempting to build the website following the directions in the ReadMe. I ran into several issues but this one I can confidently fix.
The "php" binary doesn't accept a "generate" command option but "daux" does.

Fix typo in the html generation instructions.
